In [116]:
import numpy as np

In [117]:
array = np.array([1,2,3])
array

array([1, 2, 3])

In [118]:
array_2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])

array_2.shape

(16,)

In [119]:
#The vector became a arr with 4 rows 4 columns
arr = array_2.reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [120]:
print('Shape:',arr.shape)
print('Dimension:', arr.ndim)
print('Data Type:', arr.dtype)
print('Size:', arr.size)
print('Type:', type(arr))

Shape: (4, 4)
Dimension: 2
Data Type: int64
Size: 16
Type: <class 'numpy.ndarray'>


In [121]:
#Change the data type into int32 
matrix = arr.astype(np.int32)
print('Data Type', matrix.dtype)

Data Type int32


In [122]:
#Creates a array full of 0s. It has 3 rows and 4 columns. 
#This matrix allocated in memory.
#Functions like append make memory slow.
zero_arr= np.zeros((3,4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [123]:
zero_arr[0][0]=5
zero_arr

array([[5., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [124]:
#Creates a array full of 1s. It has 3 rows and 4 columns. 
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [125]:
#Create a empty array
np.empty((4,5))

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316],
       [ 2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211],
       [ 5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105],
       [ 7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ]])

In [126]:
#Prints numbers between 0 and 100 in increments of 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [127]:
#Prints numbers between 0 and 20 in increments of 2  (20/10)=2 -- > increase amount
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [128]:
a= np.array([1,2,3])
b= np.array([4,5,6])

In [129]:
print(a+b) #[5 7 9]
print(a-b) #[-3 -3 -3]
print(a*b) #[4 10 8]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [130]:
liste = [1,2,3,4]
array = np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [131]:
array = np.array(liste)
array

array([1, 2, 3, 4])

In [132]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [133]:
#Changes index 0 of arrays a,b,c
#np.array is stored in memory as a space, not as a value..
#Since the same space is allocated in memory for 
#a,b,c, changing one of them will change all of them.

b=a

c=a

b[0]=5 
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [134]:
#Copy function allocate new space from memory
#This allows us to change any index and keep the other one
d = a.copy()


In [135]:
a= np.array([1,2,3,4,5,6,7])

In [136]:
a[0:4]

array([1, 2, 3, 4])

In [137]:
#Reverse the array
reverse_array = a[::-1]
reverse_array

array([7, 6, 5, 4, 3, 2, 1])

In [138]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# **Important**

In [139]:
# Row 1 gives the value in column 1, which is 7.
print(b[1,1]) #1.satır 1.sütundaki değer olan 7'yi verir.

#Returns all rows and column 2. [2 7]
print(b[:,1]) #satırların hepsini ve 2. sütunu verir. [2 7]

#Returns all elements in row 2. [ 6 7 8 9 10]
print(b[1,:]) #2.satırdaki elemanların tamamını verir. [ 6  7  8  9 10]

#Row 2 gives columns 2, 3, 4. [7 8 9]
print(b[1,1:4]) #2.satır 2. 3. 4. sütunları verir. [7 8 9]

#Takes the last row and all columns. [ 6 7 8 9 10]
print(b[-1,:]) #son satır ve tüm sütunları alır. [ 6  7  8  9 10]

#Takes the last column and all rows. [ 5 10]
print(b[:,-1]) #son sütun ve tüm satırlari alır. [ 5 10]

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [140]:
#Creates 3x3 matrix
array = np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print('Dimension ->',array.ndim,'\n' ,array)

Dimension -> 2 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [143]:
#With ravel function we can decreace dimensions into 1-D
a = array.ravel()
print('Dimension ->',a.ndim,'\n' ,a)

Dimension -> 1 
 [1 2 3 4 5 6 7 8 9]


In [144]:
#Gets the transpose of the array
array.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [145]:
array2 = np.array([[1,2],[3,4],[5,6]])
array2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [147]:
#Size changes made with resize are permanent.
#They are saved in the same array
#Changes made with reshape are not permanent. It must be saved in another variable
array2.resize((2,3))
array2

array([[1, 2, 3],
       [4, 5, 6]])